image: socialcars/docker:colmto

test:
  script:
  - python3 setup.py test
  only:
  - master
  - develop

run:
  script:
  - python3 setup.py bdist_wheel
  # run the command here
  artifacts:
    paths:
      - dist/*.whl
  only:
  - master

pages:
  script:
  # - pip3 install sphinx sphinx-rtd-theme
  - cd docs ; make html
  - mv build/html/ ../public/
  artifacts:
    paths:
    - public
  only:
  - master
