image: python:3.7.1-alpine

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

stages:
  - build
  - test
  - deploy

devtest:
  image: socialcars/docker:colmto
  stage: test
  script:
  - python3 setup.py test
  only:
  - develop

coverage:
  image: socialcars/docker:colmto
  stage: test
  script:
  - pytest tests --cov=colmto --junitxml=report.xml
  - codecov
  artifacts:
    reports:
      junit: report.xml
  only:
  - master
  
run:
  stage: build
  script:
  - pip3 install wheel sphinx
  - python3 setup.py bdist_wheel
  artifacts:
    paths:
      - dist/*.whl
  only:
  - master

pages:
  stage: deploy
  script:
  - apk add build-base
  - pip3 install -r https://gitlab.com/ascm/colmto/raw/master/requirements.txt
  - cd docs; make html; make latexpdf
  - mv build/html ../public
  - mv build/latex/CoLMTO-doc.pdf ../public/
  artifacts:
    paths:
    - public
  only:
  - master
