image: socialcars/docker:colmto

devtest:
  stage: test
  script:
  - python3 setup.py test
  only:
  - develop

coverage:
  stage: test
  script:
  - pytest tests --cov=colmto --junitxml=report.xml
  - codecov
  artifacts:
    reports:
      junit: report.xml
  only:
  - master
  
run:
  stage: test
  script:
  - pip3 install wheel
  - python3 setup.py bdist_wheel
  artifacts:
    paths:
      - dist/*.whl
  only:
  - master

pages:
  stage: deploy
  script:
  - pip3 install sphinx sphinx-rtd-theme
  - cd docs ; make html # ; make latexpdf
  - mv build/html ../public
  #- mv build/latex/CoLMTO-doc.pdf ../public/
  artifacts:
    paths:
    - public
  only:
  - master
