image: socialcars/docker:colmto

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"

cache:
  paths:
    - .cache/pip
    - venv/

test:
  script:
  - python setup.py test
  only:
  - master
  - develop

run:
  script:
  - python setup.py bdist_wheel
  # run the command here
  artifacts:
    paths:
      - dist/*.whl
  only:
  - master
  - develop

pages:
  script:
  - pip install sphinx sphinx-rtd-theme
  - cd docs ; make html
  - mv build/html/ ../public/
  artifacts:
    paths:
    - public
  only:
  - master
