-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 7539d8bd1a00a3c1bfd34cdb606d3a6372e83469
    hooks:
    -   id: trailing-whitespace
-   repo: git://github.com/asottile/reorder_python_imports
    sha: v0.3.0
    hooks:
    -   id: reorder-python-imports
