-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.8.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-yaml
    -   id: check-xml
    -   id: check-json
    -   id: end-of-file-fixer
