version: 2

jobs:
    build:
        working_directory: ~/colmto
        docker:
            - image: socialcars/docker:colmto
        environment:
            TZ: "/usr/share/zoneinfo/Europe/Berlin"
            GIT_AUTHOR_NAME: CircleCI
            GIT_AUTHOR_EMAIL: masc@tu-clausthal.de
            GIT_COMMITTER_NAME: CircleCI
            GIT_COMMITTER_EMAIL: masc@tu-clausthal.de
            SUMO_HOME: /opt/sumo

        branches:
            ignore:
                - develop
                - /dev-.*/
                - /gh-.*/
                - /sim-.*/

        shell: /bin/bash

        steps:
            - run:
                  name: Expand Path to $BASH_ENV
                  command: echo 'export PATH=~/.local/bin:$PATH' >> $BASH_ENV
            - checkout
            - restore_cache:
                keys:
                    - deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
            - run:
                  name: Upgrade to Latest Dependencies
                  command: pip3 install -U -r requirements.txt --user
            - save_cache:
                  key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
                  paths:
                      - ~/.local
            - run:
                  name: Install Colmto Package
                  command: python3 setup.py install --user
            - run:
                  name: Create documentation (html)
                  command: cd docs && make html && mv build/html sources; cd ..
            - run:
                  name: Create documentation (pdf)
                  command: cd docs && make latexpdf && cp build/latex/CoLMTO-doc.pdf .; cd ..
            - run:
                  name: Remove sphinx source and build files
                  command: rm -r docs/source && rm -r docs/build && rm docs/Makefile
            - run:
                name: Run Tests and Create Codecov/Codacy Coverage Report
                command: py.test tests --log-cli-level=DEBUG --cov=colmto --cov-report=xml:coverage.xml
            - run:
                  name: Upload Results to Codecov for masc (1/4)
                  command: bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
            - run:
                  name: Upload Results to Codecov for socialcars (2/4)
                  command: bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN_2
            - run:
                  name: Upload Results to Codacy for masc (3/4)
                  command: python-codacy-coverage -r coverage.xml -t $CODACY_PROJECT_TOKEN_2
            - run:
                  name: Upload Results to Codacy for socialcars (3/4)
                  command: python-codacy-coverage -r coverage.xml -t $CODACY_PROJECT_TOKEN
            - run:
                  name: Backup documentation files to /tmp
                  command: mv -f colmto tests docs readme.md license.md architecture.png executionmodel.png /tmp
            - run:
                  name: Checkout gh-pages
                  command: git checkout gh-pages || git checkout -b gh-pages
            - run:
                  name: Backup circle.yml and create new .gitignore in /tmp
                  command: mv -f circle.yml /tmp && rm .gitignore && echo -e "*.*\n!.gitignore\n!.gitmodules\n!circle.yml\n!codecov.yml\n!setup.cfg\n!colmto/resources/*.yaml\n!*.txt\n!*.py\n!*.md\n!*.png\n!build-sumo-osx.sh\n!.pre-commit-config.yaml\n!*.coveragerc\ndocs/build/**/*\n!docs/Makefile\n!docs/**/*\n!.nojekyll" >> /tmp/.gitignore
            - run:
                  name: Checkout Master
                  command: git checkout master
            - run:
                  name: Remove Remote gh-pages Branch
                  command: git push origin :gh-pages || true
            - run:
                  name: Remove Local gh-pages Branch
                  command: git branch -D gh-pages
            - run:
                  name: Checkout
                  command: git checkout --orphan gh-pages
            - run:
                  name: Remove
                  command: rm -Rf *
            - run:
                  name: Remove pre-commit-config
                  command: rm -f .pre-commit-config.yaml
            - run:
                  name: Restore documentation files from /tmp
                  command: mv -f /tmp/.gitignore /tmp/circle.yml /tmp/colmto /tmp/tests /tmp/docs /tmp/readme.md /tmp/license.md /tmp/architecture.png /tmp/executionmodel.png .
            - run:
                  name: Update pylint.md (1/4)
                  command: sh docs/pylint.sh > pylint.md || true
            - run:
                  name: Update pylint.md (2/4)
                  command: echo -e "\n## Import Graph\n" >> pylint.md
            - run:
                  name: Update pylint.md (3/4)
                  command: cp pylint.md pylint_doc.md
            - run:
                  name: Update pylint.md (4/4)
                  command: echo -e "\n![ImportGraph](https://github.com/SocialCars/colmto/blob/gh-pages/docs/sources/colmto-imports.png)" >> pylint.md
            - run:
                  name: Update report.md (1/4)
                  command: echo -e "\n# Code Statistics\n\n" > report.md
            - run:
                  name: Update readme.md
                  command: echo -e "## Copyright & License\n\n- Copyright 2017, Malte Aschermann\n- License LGPL\n\n" > readme_doc.md
            - run:
                  name: Update radon.md
                  command: sh docs/radon.sh > radon.md
            - run:
                  name: Update report.md (2/4)
                  command: cat radon.md >> report.md
            - run:
                  name: Update report.md (3/4)
                  command: echo -e "\n# Pylint\n\n" >> report.md
            - run:
                  name: Update report.md (4/4)
                  command: cat pylint.md >> report.md
            - run:
                  name: Cleanup
                  command: rm -Rf colmto tests site readme_doc.md pylint.html pylint.md pylint_doc.md radon.md
            - run:
                  name: gh-pages is not a jekyll page
                  command: touch .nojekyll
            - run:
                  name: Create index.html
                  command: echo -e "<html><head><meta http-equiv="refresh" content="0; url=https://socialcars.github.io/colmto/docs/sources/"><link rel="canonical" href="https://socialcars.github.io/colmto/docs/sources/" /></head></html>" > index.html
            - run:
                  name: Git Add All
                  command: git add --all .
            - run:
                  name: Git Commit
                  command: git commit -m "CircleCI run complete. Report https://github.com/SocialCars/colmto/blob/gh-pages/report.md , Doku http://socialcars.github.io/colmto/docs/sources/index.html"
            - run:
                  name: Git Push gh-pages
                  command: git push origin gh-pages
