sumo:
  enabled: true
  gui-delay: 200
  headless: false
  port: 8873
naive:
  enabled: false
mip:
  enabled: false
simtimeinterval: [0, 10800]
runs: 1
vtypedistribution:
  tractor:
    fraction: 0.1
    speedsigma: 1
  truck:
    fraction: 0.3
    speedsigma: 1
  passenger:
    fraction: 0.5
    speedsigma: 1
starttimedistribution: linear
nbvehicles:
  enabled: true
  value: 20
aadt:
  enabled: false
  value: 86400
vehiclespersecond:
  enabled: true
  value: 0.5
initialsorting: bestcase
