desiredspeeds:
  args: [27.77777777777778, 8.333333333333334]
  distribution: GAUSS
sumo:
  enabled: true
  gui-delay: 200
  headless: false
  port: 8873
naive:
  enabled: false
mip:
  enabled: false
simtimeinterval: [0, 10800]
runs: 1
vtypedistribution:
  tractors: 0.1
  trucks: 0.2
  passenger: 0.7
initialsorting: bestcase
