sumo:
  enabled: true
  gui-delay: 200
  headless: false
  port: 8873
simtimeinterval: [0, 60]
runs: 1
scenarios: [BW-B292]
vtypedistribution:
  tractor:
    fraction: 0.2
    speedDev: 0.0
    desiredSpeeds: [7.0, 8.0, 9.0, 10.0]
  truck:
    fraction: 0.3
    speedDev: 0.0
    desiredSpeed: [22.0, 23.0, 24.0, 25.0]
  passenger:
    fraction: 0.5
    speedDev: 0.0
    desiredSpeed: [31.0, 32.0, 33.0, 34.0]
starttimedistribution: poisson
nbvehicles:
  enabled: false
  value: 20
aadt:
  enabled: false
  value: 108000 # = 4500 vehicles/hour
vehiclespersecond:
  enabled: false
  value: 0.5
initialsortings: [best, random, worst]
detectors:
  start: true
  splits: true
  end: true
  otl: true