sumo:
  enabled: true
  gui-delay: 200
  headless: true
  port: 8873
simtimeinterval: [0, 600]
runs: 1
scenarios: [Irzik1]
vtypedistribution:
  tractor:
    fraction: 0.2
    speedDev: 0.0
    desiredSpeeds: [8.0]
  truck:
    fraction: 0.3
    speedDev: 0.0
    desiredSpeeds: [23.0]
  passenger:
    fraction: 0.5
    speedDev: 0.0
    desiredSpeeds: [34.0]
starttimedistribution: poisson
nbvehicles:
  enabled: false
  value: 30
aadt:
  enabled: true
  value: 13000 # = 541 vehicles/hour
vehiclespersecond:
  enabled: false
  value: 0.5
initialsortings: [random]
detectors:
  start: true
  splits: true
  end: true
  otl: true
