sumo:
  enabled: false
  gui-delay: 200
  headless: false
  port: 8873
cse:
  enabled: true
mip:
  enabled: false
simtimeinterval: [0, 60]
runs: 1
scenarios: [CSE-Test]
vtypedistribution:
  tractor:
    fraction: 0.2
    speedDev: 0.0
    desiredSpeed: 8.0
    length: 4.0
  truck:
    fraction: 0.3
    speedDev: 0.0
    desiredSpeed: 24.0
    length: 4.0
  passenger:
    fraction: 0.5
    speedDev: 0.0
    desiredSpeed: 32.0
    length: 4.0
starttimedistribution: poisson
nbvehicles:
  enabled: true
  value: 20
aadt:
  enabled: false
  value: 86400
vehiclespersecond:
  enabled: true
  value: 0.5
initialsortings: [best, random, worst]
detectors:
  start: true
  splits: true
  end: true
  otl: false