BW-B292-Aglasterhausen-Obrigheim:
  description:
    from: Aglasterhausen
    road: B292
    state: BW
    to: Obrigheim
  parameters:
    aadt: 12870
    length: 7800.0
    maxSpeed: 27.77777777777778
    switches: 8
    type: GT
BW-B31n-Stockach-Ueberlingen:
  description:
    from: Stockach
    road: B31n
    state: BW
    to: Ueberlingen
  parameters:
    aadt: 12700
    length: 10000.0
    maxSpeed: 33.333333333333336
    switches: 4
    type: TLE
BW-B33-Gengenbach-Biberach:
  description:
    from: Gengenbach
    road: B33
    state: BW
    to: Biberach
  parameters:
    aadt: 18000
    length: 5600.0
    maxSpeed: 27.77777777777778
    switches: 4
    type: TLE
