delivery:
  accel: 2.9
  decel: 7.5
  height: 2.86
  length: 6.5
  maxSpeed: 50.0
  minGap: 2.5
  speedDev: 0.1
  speedFactor: 1
  vClass: delivery
  width: 2.16
heavytransport:
  accel: 1.3
  decel: 4.0
  height: 2.4
  length: 7.1
  maxSpeed: 11.11111111111111
  minGap: 2.5
  speedDev: 0.1
  speedFactor: 1
  vClass: trailer
  width: 2.4
passenger:
  accel: 2.9
  decel: 7.5
  height: 1.5
  length: 4.3
  maxSpeed: 50.0
  minGap: 2.5
  speedDev: 0.1
  speedFactor: 1
  vClass: passenger
  width: 1.8
tractor:
  accel: 1.3
  decel: 4.0
  height: 2.4
  length: 3.0
  maxSpeed: 8.333333333333334
  minGap: 2.5
  speedDev: 0.1
  speedFactor: 1
  vClass: tractor
  width: 2.4
truck:
  accel: 1.3
  decel: 4.0
  height: 2.4
  length: 7.1
  maxSpeed: 36.11111111111111
  minGap: 2.5
  speedDev: 0.1
  speedFactor: 1
  vClass: truck
  width: 2.4
van:
  accel: 2.9
  decel: 7.5
  height: 1.73
  length: 4.7
  maxSpeed: 50.0
  minGap: 2.5
  speedDev: 0.1
  speedFactor: 1
  vClass: delivery
  width: 1.9
